name: build-container
on:
  push:
    branches:
      - master
      - dev
    paths:
      - Dockerfile
      - requirements.txt
  pull_request:
    branches:
      - master
      - dev
    paths:
      - Dockerfile
      - requirements.txt

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      TMPDIR: /mnt/docker
      DOCKER_BUILDKIT: 1
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check space
        run: df -h

      - name: Free disk space (specific to Ubuntu images)
        run: |
          sudo apt-get remove --purge -y microsoft-edge-stable google-chrome-stable firefox azure-cli '^google-cloud-*' powershell temurin-{8,11,17,25}-jdk '^llvm-*' '^libllvm-*' '^mysql-*' gcc-{9,10,11,12,13} '^gfortran-*' '^dotnet-.*'
          sudo apt-get autoremove -y
          sudo apt-get clean
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100

      - name: Check space
        run: df -h

      - name: Free disk space (specific to Ubuntu images)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/local/lib/android

      - name: Check space
        run: df -h
          #
          #      - name: TEST
          #        run: |
          #          du -shc /opt/*
          #          ls -l /mnt
          #          cat /mnt/DATALOSS_WARNING_README.txt
          #          echo "TMPDIR" "$TMPDIR"
          #          sudo mkdir -p "$TMPDIR"
          #          sudo chown runner:runner "$TMPDIR"
          #          id
          #          ls -l /mnt
          #          ls "$TMPDIR"
          #          echo "$RUNNER_TEMP"
          #          echo "runner"; du -shc /home/runner/work/_temp/
          #          echo "docker"; sudo du -shc /var/lib/docker/
          #
          #      - name: Log in to the Container registry
          #        uses: docker/login-action@v3
          #        with:
          #          registry: ghcr.io
          #          username: '${{ github.actor }}'
          #          password: '${{ secrets.GITHUB_TOKEN }}'
          #
          #      - name: Set up QEMU
          #        uses: docker/setup-qemu-action@v3
          #
          #      - name: Set up Docker Buildx
          #        uses: docker/setup-buildx-action@v3
          #
          #      - name: Build and push
          #        uses: docker/build-push-action@v6
          #        with:
          #          file: Dockerfile
          #          platforms: linux/amd64
          #          push: false
          #          tags: ${{ github.repository }}:test
          #          cache-from: type=gha
          #          cache-to: type=gha,mode=max
          #
          #      - name: Clean temp
          #        run: |
          #          df -h
          #          echo "runner"; du -shc /home/runner/work/_temp/
          #          echo "docker"; sudo du -shc /var/lib/docker/
          #          echo "mnt"; du -shc /mnt/docker/
          #          ls -l /mnt/docker
          #          sudo rm -rf /mnt/docker
